"use server";

import { prisma } from "@/lib/prisma";
import { auth, clerkClient } from "@clerk/nextjs/server";

const ADMIN_EMAIL = "maildmz@gmail.com";

async function verifyAdmin(): Promise<boolean> {
    const { userId } = await auth();
    if (!userId) return false;

    try {
        const client = await clerkClient();
        const user = await client.users.getUser(userId);
        const primaryEmail = user.emailAddresses.find(
            (e) => e.id === user.primaryEmailAddressId
        );
        return primaryEmail?.emailAddress === ADMIN_EMAIL;
    } catch {
        return false;
    }
}

export interface AdminStats {
    totalUsers: number;
    totalProjects: number;
    totalFeatures: number;
    totalSpecifications: number;
    totalMessages: number;
    totalArtifacts: number;
    totalSourceDocuments: number;
    autoGeneratedFeatures: number;
    autoGeneratedSpecs: number;
}

export interface ProjectInfo {
    id: string;
    name: string;
    userId: string | null;
    organizationId: string | null;
    methodology: string;
    createdAt: string;
    featureCount: number;
    specificationCount: number;
    sourceDocumentCount: number;
}

export interface SourceDocumentInfo {
    id: string;
    projectId: string;
    projectName: string;
    fileName: string;
    fileType: string;
    fileSize: number;
    status: string;
    extractionStatus: string;
    createdAt: string;
}

export async function getAdminStats(): Promise<AdminStats | null> {
    if (!(await verifyAdmin())) return null;

    const [
        totalProjects,
        totalFeatures,
        totalSpecifications,
        totalMessages,
        totalArtifacts,
        totalSourceDocuments,
        autoGeneratedFeatures,
        autoGeneratedSpecs,
    ] = await Promise.all([
        prisma.project.count(),
        prisma.feature.count(),
        prisma.specification.count(),
        prisma.message.count(),
        prisma.artifact.count(),
        prisma.projectSourceDocument.count(),
        prisma.feature.count({ where: { isAutoGenerated: true } }),
        prisma.specification.count({ where: { isAutoGenerated: true } }),
    ]);

    // Count unique userIds from projects
    const uniqueUsers = await prisma.project.findMany({
        select: { userId: true },
        distinct: ["userId"],
        where: { userId: { not: null } },
    });

    return {
        totalUsers: uniqueUsers.length,
        totalProjects,
        totalFeatures,
        totalSpecifications,
        totalMessages,
        totalArtifacts,
        totalSourceDocuments,
        autoGeneratedFeatures,
        autoGeneratedSpecs,
    };
}

export async function getAllProjects(): Promise<ProjectInfo[] | null> {
    if (!(await verifyAdmin())) return null;

    const projects = await prisma.project.findMany({
        include: {
            _count: {
                select: {
                    features: true,
                    specifications: true,
                    sourceDocuments: true,
                },
            },
        },
        orderBy: { createdAt: "desc" },
    });

    return projects.map((p) => ({
        id: p.id,
        name: p.name,
        userId: p.userId,
        organizationId: p.organizationId,
        methodology: p.methodology,
        createdAt: p.createdAt.toISOString(),
        featureCount: p._count.features,
        specificationCount: p._count.specifications,
        sourceDocumentCount: p._count.sourceDocuments,
    }));
}

export async function getAllSourceDocuments(): Promise<SourceDocumentInfo[] | null> {
    if (!(await verifyAdmin())) return null;

    const documents = await prisma.projectSourceDocument.findMany({
        include: {
            project: {
                select: { name: true },
            },
        },
        orderBy: { createdAt: "desc" },
    });

    return documents.map((d) => ({
        id: d.id,
        projectId: d.projectId,
        projectName: d.project.name,
        fileName: d.fileName,
        fileType: d.fileType,
        fileSize: d.fileSize,
        status: d.status,
        extractionStatus: d.extractionStatus,
        createdAt: d.createdAt.toISOString(),
    }));
}

export async function adminDeleteProject(projectId: string): Promise<boolean> {
    if (!(await verifyAdmin())) return false;

    try {
        await prisma.project.delete({ where: { id: projectId } });
        return true;
    } catch (error) {
        console.error("Failed to delete project:", error);
        return false;
    }
}

export async function adminDeleteSourceDocument(documentId: string): Promise<boolean> {
    if (!(await verifyAdmin())) return false;

    try {
        await prisma.projectSourceDocument.delete({ where: { id: documentId } });
        return true;
    } catch (error) {
        console.error("Failed to delete source document:", error);
        return false;
    }
}

export async function adminDeleteAllAutoGenerated(): Promise<{ features: number; specs: number } | null> {
    if (!(await verifyAdmin())) return null;

    try {
        // Delete specs first due to FK constraints
        const specs = await prisma.specification.deleteMany({
            where: { isAutoGenerated: true },
        });

        const features = await prisma.feature.deleteMany({
            where: { isAutoGenerated: true },
        });

        return { features: features.count, specs: specs.count };
    } catch (error) {
        console.error("Failed to delete auto-generated content:", error);
        return null;
    }
}

export async function adminCleanupOrphanedData(): Promise<{
    deletedFeatures: number;
    deletedSpecs: number;
    deletedMessages: number;
    deletedArtifacts: number;
} | null> {
    if (!(await verifyAdmin())) return null;

    try {
        // Get all valid project IDs
        const validProjectIds = (await prisma.project.findMany({ select: { id: true } })).map(p => p.id);

        // Get all valid specification IDs
        const validSpecIds = (await prisma.specification.findMany({ select: { id: true } })).map(s => s.id);

        // Delete features that reference non-existent projects
        const deletedFeatures = await prisma.feature.deleteMany({
            where: {
                projectId: { notIn: validProjectIds },
            },
        });

        // Delete specs that reference non-existent projects
        const deletedSpecs = await prisma.specification.deleteMany({
            where: {
                projectId: { notIn: validProjectIds },
            },
        });

        // Delete messages that reference non-existent specifications
        const deletedMessages = await prisma.message.deleteMany({
            where: {
                specificationId: { notIn: validSpecIds },
            },
        });

        // Delete artifacts that reference non-existent specifications
        const deletedArtifacts = await prisma.artifact.deleteMany({
            where: {
                specificationId: { notIn: validSpecIds },
            },
        });

        return {
            deletedFeatures: deletedFeatures.count,
            deletedSpecs: deletedSpecs.count,
            deletedMessages: deletedMessages.count,
            deletedArtifacts: deletedArtifacts.count,
        };
    } catch (error) {
        console.error("Failed to cleanup orphaned data:", error);
        return null;
    }
}

export async function adminDeleteAllData(): Promise<boolean> {
    if (!(await verifyAdmin())) return false;

    try {
        // Delete in order to respect FK constraints
        await prisma.extractedItem.deleteMany({});
        await prisma.artifact.deleteMany({});
        await prisma.message.deleteMany({});
        await prisma.specificationDocument.deleteMany({});
        await prisma.specification.deleteMany({});
        await prisma.phase.deleteMany({});
        await prisma.feature.deleteMany({});
        await prisma.projectSourceDocument.deleteMany({});
        await prisma.projectDocument.deleteMany({});
        await prisma.projectExpert.deleteMany({});
        await prisma.project.deleteMany({});
        return true;
    } catch (error) {
        console.error("Failed to delete all data:", error);
        return false;
    }
}
