"use server";

import { prisma } from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import {
    uploadToR2,
    deleteFromR2,
    generateProjectStorageKey,
    getMimeType,
} from "@/lib/r2";
import { extractText, getFileType } from "@/lib/text-extraction";

// Types
export interface ProjectSourceDocumentData {
    id: string;
    projectId: string;
    fileName: string;
    fileType: string;
    fileSize: number;
    status: string;
    extractionStatus: string;
    extractedText: string | null;
    extractedFeatures: ExtractedFeature[] | null;
    extractedSpecs: ExtractedSpecGroup[] | null;
    error: string | null;
    createdAt: string;
}

export interface ExtractedFeature {
    name: string;
    description: string;
    documentContext: string;
}

export interface ExtractedSpec {
    name: string;
    initialDescription: string;
    documentContext: string;
}

export interface ExtractedSpecGroup {
    featureName: string;
    specifications: ExtractedSpec[];
}

export interface AutoGeneratedStats {
    features: number;
    specifications: number;
    documents: number;
}

/**
 * Get all source documents for a project
 */
export async function getProjectSourceDocuments(
    projectId: string
): Promise<ProjectSourceDocumentData[]> {
    const { userId, orgId } = await auth();
    if (!userId) throw new Error("Unauthorized");

    // Verify access to project
    const project = await prisma.project.findUnique({
        where: { id: projectId },
    });

    if (!project) throw new Error("Project not found");

    const hasAccess =
        project.userId === userId ||
        (orgId && project.organizationId === orgId);
    if (!hasAccess) throw new Error("Unauthorized");

    const documents = await prisma.projectSourceDocument.findMany({
        where: { projectId },
        orderBy: { createdAt: "desc" },
    });

    return documents.map((doc) => ({
        id: doc.id,
        projectId: doc.projectId,
        fileName: doc.fileName,
        fileType: doc.fileType,
        fileSize: doc.fileSize,
        status: doc.status,
        extractionStatus: doc.extractionStatus,
        extractedText: doc.extractedText,
        extractedFeatures: doc.extractedFeatures as ExtractedFeature[] | null,
        extractedSpecs: doc.extractedSpecs as ExtractedSpecGroup[] | null,
        error: doc.error,
        createdAt: doc.createdAt.toISOString(),
    }));
}

/**
 * Get a single source document
 */
export async function getProjectSourceDocument(
    documentId: string
): Promise<ProjectSourceDocumentData | null> {
    const { userId, orgId } = await auth();
    if (!userId) throw new Error("Unauthorized");

    const document = await prisma.projectSourceDocument.findUnique({
        where: { id: documentId },
        include: { project: true },
    });

    if (!document) return null;

    const hasAccess =
        document.project.userId === userId ||
        (orgId && document.project.organizationId === orgId);
    if (!hasAccess) throw new Error("Unauthorized");

    return {
        id: document.id,
        projectId: document.projectId,
        fileName: document.fileName,
        fileType: document.fileType,
        fileSize: document.fileSize,
        status: document.status,
        extractionStatus: document.extractionStatus,
        extractedText: document.extractedText,
        extractedFeatures: document.extractedFeatures as ExtractedFeature[] | null,
        extractedSpecs: document.extractedSpecs as ExtractedSpecGroup[] | null,
        error: document.error,
        createdAt: document.createdAt.toISOString(),
    };
}

/**
 * Upload a source document and start text extraction
 */
export async function uploadProjectSourceDocument(
    projectId: string,
    formData: FormData
): Promise<ProjectSourceDocumentData> {
    const { userId, orgId } = await auth();
    if (!userId) throw new Error("Unauthorized");

    // Verify access to project
    const project = await prisma.project.findUnique({
        where: { id: projectId },
    });

    if (!project) throw new Error("Project not found");

    const hasAccess =
        project.userId === userId ||
        (orgId && project.organizationId === orgId);
    if (!hasAccess) throw new Error("Unauthorized");

    // Get file from form data
    const file = formData.get("file") as File;
    if (!file) throw new Error("No file provided");

    // Validate file type
    const fileType = getFileType(file.name);

    // Validate file size (max 10MB)
    const maxSize = 10 * 1024 * 1024;
    if (file.size > maxSize) {
        throw new Error("File too large. Maximum size is 10MB.");
    }

    // Convert to buffer
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Generate storage key and upload to R2
    const storageKey = generateProjectStorageKey(projectId, file.name);
    const mimeType = getMimeType(file.name);

    await uploadToR2(storageKey, buffer, mimeType);

    // Create document record
    const document = await prisma.projectSourceDocument.create({
        data: {
            projectId,
            fileName: file.name,
            fileType,
            fileSize: file.size,
            storageKey,
            status: "processing",
            extractionStatus: "pending",
        },
    });

    // Extract text in background (don't await)
    extractAndSaveText(document.id, buffer, fileType).catch(console.error);

    revalidatePath(`/project/${projectId}`);

    return {
        id: document.id,
        projectId: document.projectId,
        fileName: document.fileName,
        fileType: document.fileType,
        fileSize: document.fileSize,
        status: document.status,
        extractionStatus: document.extractionStatus,
        extractedText: document.extractedText,
        extractedFeatures: null,
        extractedSpecs: null,
        error: document.error,
        createdAt: document.createdAt.toISOString(),
    };
}

/**
 * Extract text from a document and save it
 */
async function extractAndSaveText(
    documentId: string,
    buffer: Buffer,
    fileType: string
): Promise<void> {
    try {
        const extractedText = await extractText(buffer, fileType);

        await prisma.projectSourceDocument.update({
            where: { id: documentId },
            data: {
                extractedText,
                status: "extracted",
            },
        });
    } catch (error) {
        console.error("Text extraction error:", error);
        await prisma.projectSourceDocument.update({
            where: { id: documentId },
            data: {
                status: "error",
                error: error instanceof Error ? error.message : "Extraction failed",
            },
        });
    }
}

/**
 * Delete a source document
 */
export async function deleteProjectSourceDocument(
    documentId: string
): Promise<void> {
    const { userId, orgId } = await auth();
    if (!userId) throw new Error("Unauthorized");

    const document = await prisma.projectSourceDocument.findUnique({
        where: { id: documentId },
        include: { project: true },
    });

    if (!document) throw new Error("Document not found");

    const hasAccess =
        document.project.userId === userId ||
        (orgId && document.project.organizationId === orgId);
    if (!hasAccess) throw new Error("Unauthorized");

    // Delete from R2
    try {
        await deleteFromR2(document.storageKey);
    } catch (error) {
        console.error("R2 delete error:", error);
        // Continue with DB deletion even if R2 fails
    }

    // Delete from database
    await prisma.projectSourceDocument.delete({
        where: { id: documentId },
    });

    revalidatePath(`/project/${document.projectId}`);
}

/**
 * Update extraction status
 */
export async function updateExtractionStatus(
    documentId: string,
    status: string,
    data?: {
        extractedFeatures?: ExtractedFeature[];
        extractedSpecs?: ExtractedSpecGroup[];
        error?: string;
    }
): Promise<void> {
    await prisma.projectSourceDocument.update({
        where: { id: documentId },
        data: {
            extractionStatus: status,
            ...(data?.extractedFeatures && { extractedFeatures: JSON.parse(JSON.stringify(data.extractedFeatures)) }),
            ...(data?.extractedSpecs && { extractedSpecs: JSON.parse(JSON.stringify(data.extractedSpecs)) }),
            ...(data?.error && { error: data.error }),
        },
    });
}

/**
 * Get auto-generated content stats for a project
 */
export async function getAutoGeneratedStats(
    projectId: string
): Promise<AutoGeneratedStats> {
    const { userId, orgId } = await auth();
    if (!userId) throw new Error("Unauthorized");

    // Verify access to project
    const project = await prisma.project.findUnique({
        where: { id: projectId },
    });

    if (!project) throw new Error("Project not found");

    const hasAccess =
        project.userId === userId ||
        (orgId && project.organizationId === orgId);
    if (!hasAccess) throw new Error("Unauthorized");

    const [features, specifications, documents] = await Promise.all([
        prisma.feature.count({
            where: { projectId, isAutoGenerated: true },
        }),
        prisma.specification.count({
            where: { projectId, isAutoGenerated: true },
        }),
        prisma.projectSourceDocument.count({
            where: { projectId },
        }),
    ]);

    return { features, specifications, documents };
}

/**
 * Delete all auto-generated content for a project
 */
export async function deleteAllAutoGeneratedContent(
    projectId: string
): Promise<{ featuresDeleted: number; specificationsDeleted: number }> {
    const { userId, orgId } = await auth();
    if (!userId) throw new Error("Unauthorized");

    // Verify access to project
    const project = await prisma.project.findUnique({
        where: { id: projectId },
    });

    if (!project) throw new Error("Project not found");

    const hasAccess =
        project.userId === userId ||
        (orgId && project.organizationId === orgId);
    if (!hasAccess) throw new Error("Unauthorized");

    // Delete specs first (due to FK constraints with features)
    const specsResult = await prisma.specification.deleteMany({
        where: { projectId, isAutoGenerated: true },
    });

    const featuresResult = await prisma.feature.deleteMany({
        where: { projectId, isAutoGenerated: true },
    });

    revalidatePath(`/project/${projectId}`);

    return {
        featuresDeleted: featuresResult.count,
        specificationsDeleted: specsResult.count,
    };
}

/**
 * Apply extracted content - create features and specifications
 */
export async function applyExtractedContent(
    documentId: string
): Promise<{ featuresCreated: number; specificationsCreated: number }> {
    const { userId, orgId } = await auth();
    if (!userId) throw new Error("Unauthorized");

    const document = await prisma.projectSourceDocument.findUnique({
        where: { id: documentId },
        include: { project: true },
    });

    if (!document) throw new Error("Document not found");

    const hasAccess =
        document.project.userId === userId ||
        (orgId && document.project.organizationId === orgId);
    if (!hasAccess) throw new Error("Unauthorized");

    if (document.extractionStatus !== "complete") {
        throw new Error("Extraction not complete");
    }

    const extractedFeatures = document.extractedFeatures as ExtractedFeature[] | null;
    const extractedSpecs = document.extractedSpecs as ExtractedSpecGroup[] | null;

    if (!extractedFeatures || extractedFeatures.length === 0) {
        throw new Error("No features extracted");
    }

    let featuresCreated = 0;
    let specificationsCreated = 0;

    // Get current max order for features
    const maxFeatureOrder = await prisma.feature.findFirst({
        where: { projectId: document.projectId },
        orderBy: { order: "desc" },
        select: { order: true },
    });

    let featureOrder = (maxFeatureOrder?.order ?? -1) + 1;

    // Create features and their specifications
    for (const extractedFeature of extractedFeatures) {
        // Create feature
        const feature = await prisma.feature.create({
            data: {
                projectId: document.projectId,
                name: extractedFeature.name,
                description: extractedFeature.description,
                order: featureOrder++,
                isAutoGenerated: true,
                sourceDocumentId: documentId,
            },
        });
        featuresCreated++;

        // Find specs for this feature
        const featureSpecs = extractedSpecs?.find(
            (sg) => sg.featureName === extractedFeature.name
        );

        if (featureSpecs && featureSpecs.specifications.length > 0) {
            let specOrder = 0;
            for (const spec of featureSpecs.specifications) {
                await prisma.specification.create({
                    data: {
                        projectId: document.projectId,
                        featureId: feature.id,
                        name: spec.name,
                        initialDescription: spec.initialDescription,
                        order: specOrder++,
                        isAutoGenerated: true,
                        sourceDocumentId: documentId,
                    },
                });
                specificationsCreated++;
            }
        }
    }

    revalidatePath(`/project/${document.projectId}`);

    return { featuresCreated, specificationsCreated };
}
