"use client";

import { useEffect, useState, useCallback } from "react";
import { useUser } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import {
    Shield,
    Database,
    Trash2,
    RefreshCw,
    Loader2,
    AlertTriangle,
    FileText,
    Layers,
    MessageSquare,
    Sparkles,
    FolderOpen,
    Users,
    ChevronDown,
    ChevronUp,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import {
    getAdminStats,
    getAllProjects,
    getAllSourceDocuments,
    adminDeleteProject,
    adminDeleteSourceDocument,
    adminDeleteAllAutoGenerated,
    adminCleanupOrphanedData,
    adminDeleteAllData,
    AdminStats,
    ProjectInfo,
    SourceDocumentInfo,
} from "@/app/actions/admin";

const ADMIN_EMAIL = "maildmz@gmail.com";

function formatBytes(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });
}

export default function AdminPage() {
    const { user, isLoaded } = useUser();
    const router = useRouter();

    const [stats, setStats] = useState<AdminStats | null>(null);
    const [projects, setProjects] = useState<ProjectInfo[] | null>(null);
    const [sourceDocuments, setSourceDocuments] = useState<SourceDocumentInfo[] | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [isRefreshing, setIsRefreshing] = useState(false);

    // Expanded sections
    const [showProjects, setShowProjects] = useState(false);
    const [showSourceDocs, setShowSourceDocs] = useState(false);

    // Confirm dialogs
    const [deleteProjectId, setDeleteProjectId] = useState<string | null>(null);
    const [deleteSourceDocId, setDeleteSourceDocId] = useState<string | null>(null);
    const [showDeleteAutoGenerated, setShowDeleteAutoGenerated] = useState(false);
    const [showCleanupOrphaned, setShowCleanupOrphaned] = useState(false);
    const [showDeleteAll, setShowDeleteAll] = useState(false);
    const [isDeleting, setIsDeleting] = useState(false);

    // Check if user is admin
    const isAdmin = user?.emailAddresses.some(
        (e) => e.emailAddress === ADMIN_EMAIL
    );

    const loadData = useCallback(async () => {
        const [statsData, projectsData, docsData] = await Promise.all([
            getAdminStats(),
            getAllProjects(),
            getAllSourceDocuments(),
        ]);
        setStats(statsData);
        setProjects(projectsData);
        setSourceDocuments(docsData);
        setIsLoading(false);
    }, []);

    useEffect(() => {
        if (isLoaded && !isAdmin) {
            router.replace("/dashboard");
            return;
        }

        if (isLoaded && isAdmin) {
            loadData();
        }
    }, [isLoaded, isAdmin, router, loadData]);

    const handleRefresh = async () => {
        setIsRefreshing(true);
        await loadData();
        setIsRefreshing(false);
    };

    const handleDeleteProject = async () => {
        if (!deleteProjectId) return;
        setIsDeleting(true);
        await adminDeleteProject(deleteProjectId);
        setDeleteProjectId(null);
        setIsDeleting(false);
        await loadData();
    };

    const handleDeleteSourceDoc = async () => {
        if (!deleteSourceDocId) return;
        setIsDeleting(true);
        await adminDeleteSourceDocument(deleteSourceDocId);
        setDeleteSourceDocId(null);
        setIsDeleting(false);
        await loadData();
    };

    const handleDeleteAutoGenerated = async () => {
        setIsDeleting(true);
        const result = await adminDeleteAllAutoGenerated();
        setShowDeleteAutoGenerated(false);
        setIsDeleting(false);
        if (result) {
            alert(`Deleted ${result.features} features and ${result.specs} specifications`);
        }
        await loadData();
    };

    const handleCleanupOrphaned = async () => {
        setIsDeleting(true);
        const result = await adminCleanupOrphanedData();
        setShowCleanupOrphaned(false);
        setIsDeleting(false);
        if (result) {
            alert(
                `Cleaned up: ${result.deletedFeatures} features, ${result.deletedSpecs} specs, ${result.deletedMessages} messages, ${result.deletedArtifacts} artifacts`
            );
        }
        await loadData();
    };

    const handleDeleteAll = async () => {
        setIsDeleting(true);
        await adminDeleteAllData();
        setShowDeleteAll(false);
        setIsDeleting(false);
        await loadData();
    };

    if (!isLoaded || isLoading) {
        return (
            <div className="flex items-center justify-center min-h-screen">
                <Loader2 className="h-8 w-8 animate-spin text-gray-400" />
            </div>
        );
    }

    if (!isAdmin) {
        return null;
    }

    return (
        <div className="p-8 max-w-6xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-8">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-red-100 rounded-lg">
                        <Shield className="h-6 w-6 text-red-600" />
                    </div>
                    <div>
                        <h1 className="text-2xl font-semibold text-gray-900">Admin Panel</h1>
                        <p className="text-sm text-gray-500">System administration and data management</p>
                    </div>
                </div>
                <Button
                    variant="outline"
                    onClick={handleRefresh}
                    disabled={isRefreshing}
                >
                    <RefreshCw className={`h-4 w-4 mr-2 ${isRefreshing ? "animate-spin" : ""}`} />
                    Refresh
                </Button>
            </div>

            {/* Stats Grid */}
            {stats && (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                    <StatCard icon={Users} label="Users" value={stats.totalUsers} />
                    <StatCard icon={FolderOpen} label="Projects" value={stats.totalProjects} />
                    <StatCard icon={Layers} label="Features" value={stats.totalFeatures} />
                    <StatCard icon={FileText} label="Specifications" value={stats.totalSpecifications} />
                    <StatCard icon={MessageSquare} label="Messages" value={stats.totalMessages} />
                    <StatCard icon={Database} label="Artifacts" value={stats.totalArtifacts} />
                    <StatCard icon={FileText} label="Source Docs" value={stats.totalSourceDocuments} />
                    <StatCard
                        icon={Sparkles}
                        label="Auto-Generated"
                        value={`${stats.autoGeneratedFeatures}F / ${stats.autoGeneratedSpecs}S`}
                        highlight
                    />
                </div>
            )}

            {/* Danger Zone */}
            <div className="bg-red-50 border border-red-200 rounded-lg p-6 mb-8">
                <h2 className="text-lg font-medium text-red-900 mb-4 flex items-center gap-2">
                    <AlertTriangle className="h-5 w-5" />
                    Danger Zone
                </h2>
                <div className="flex flex-wrap gap-3">
                    <Button
                        variant="outline"
                        onClick={() => setShowDeleteAutoGenerated(true)}
                        className="text-red-600 border-red-200 hover:bg-red-100"
                    >
                        <Sparkles className="h-4 w-4 mr-2" />
                        Delete All Auto-Generated
                    </Button>
                    <Button
                        variant="outline"
                        onClick={() => setShowCleanupOrphaned(true)}
                        className="text-orange-600 border-orange-200 hover:bg-orange-100"
                    >
                        <RefreshCw className="h-4 w-4 mr-2" />
                        Cleanup Orphaned Data
                    </Button>
                    <Button
                        variant="outline"
                        onClick={() => setShowDeleteAll(true)}
                        className="text-red-600 border-red-200 hover:bg-red-100"
                    >
                        <Trash2 className="h-4 w-4 mr-2" />
                        Delete ALL Data
                    </Button>
                </div>
            </div>

            {/* Projects Section */}
            <div className="border border-gray-200 rounded-lg mb-4">
                <button
                    onClick={() => setShowProjects(!showProjects)}
                    className="w-full flex items-center justify-between p-4 hover:bg-gray-50 transition-colors"
                >
                    <div className="flex items-center gap-2">
                        <FolderOpen className="h-5 w-5 text-gray-600" />
                        <span className="font-medium text-gray-900">
                            Projects ({projects?.length || 0})
                        </span>
                    </div>
                    {showProjects ? (
                        <ChevronUp className="h-5 w-5 text-gray-400" />
                    ) : (
                        <ChevronDown className="h-5 w-5 text-gray-400" />
                    )}
                </button>
                {showProjects && projects && (
                    <div className="border-t border-gray-200 max-h-96 overflow-y-auto">
                        <table className="w-full text-sm">
                            <thead className="bg-gray-50 sticky top-0">
                                <tr>
                                    <th className="text-left p-3 font-medium text-gray-700">Name</th>
                                    <th className="text-left p-3 font-medium text-gray-700">User ID</th>
                                    <th className="text-left p-3 font-medium text-gray-700">Methodology</th>
                                    <th className="text-center p-3 font-medium text-gray-700">F / S / D</th>
                                    <th className="text-left p-3 font-medium text-gray-700">Created</th>
                                    <th className="text-right p-3 font-medium text-gray-700">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {projects.map((project) => (
                                    <tr key={project.id} className="border-t border-gray-100 hover:bg-gray-50">
                                        <td className="p-3 font-medium text-gray-900">{project.name}</td>
                                        <td className="p-3 text-gray-500 font-mono text-xs">
                                            {project.userId?.slice(0, 12)}...
                                        </td>
                                        <td className="p-3">
                                            <span className="px-2 py-1 bg-gray-100 rounded text-xs">
                                                {project.methodology}
                                            </span>
                                        </td>
                                        <td className="p-3 text-center text-gray-600">
                                            {project.featureCount} / {project.specificationCount} / {project.sourceDocumentCount}
                                        </td>
                                        <td className="p-3 text-gray-500 text-xs">
                                            {formatDate(project.createdAt)}
                                        </td>
                                        <td className="p-3 text-right">
                                            <button
                                                onClick={() => setDeleteProjectId(project.id)}
                                                className="p-1 text-red-500 hover:bg-red-50 rounded"
                                            >
                                                <Trash2 className="h-4 w-4" />
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

            {/* Source Documents Section */}
            <div className="border border-gray-200 rounded-lg">
                <button
                    onClick={() => setShowSourceDocs(!showSourceDocs)}
                    className="w-full flex items-center justify-between p-4 hover:bg-gray-50 transition-colors"
                >
                    <div className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-gray-600" />
                        <span className="font-medium text-gray-900">
                            Source Documents ({sourceDocuments?.length || 0})
                        </span>
                    </div>
                    {showSourceDocs ? (
                        <ChevronUp className="h-5 w-5 text-gray-400" />
                    ) : (
                        <ChevronDown className="h-5 w-5 text-gray-400" />
                    )}
                </button>
                {showSourceDocs && sourceDocuments && (
                    <div className="border-t border-gray-200 max-h-96 overflow-y-auto">
                        <table className="w-full text-sm">
                            <thead className="bg-gray-50 sticky top-0">
                                <tr>
                                    <th className="text-left p-3 font-medium text-gray-700">File Name</th>
                                    <th className="text-left p-3 font-medium text-gray-700">Project</th>
                                    <th className="text-left p-3 font-medium text-gray-700">Type</th>
                                    <th className="text-left p-3 font-medium text-gray-700">Size</th>
                                    <th className="text-left p-3 font-medium text-gray-700">Status</th>
                                    <th className="text-left p-3 font-medium text-gray-700">Created</th>
                                    <th className="text-right p-3 font-medium text-gray-700">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {sourceDocuments.map((doc) => (
                                    <tr key={doc.id} className="border-t border-gray-100 hover:bg-gray-50">
                                        <td className="p-3 font-medium text-gray-900 max-w-48 truncate">
                                            {doc.fileName}
                                        </td>
                                        <td className="p-3 text-gray-600">{doc.projectName}</td>
                                        <td className="p-3">
                                            <span className="px-2 py-1 bg-gray-100 rounded text-xs uppercase">
                                                {doc.fileType}
                                            </span>
                                        </td>
                                        <td className="p-3 text-gray-500">{formatBytes(doc.fileSize)}</td>
                                        <td className="p-3">
                                            <span
                                                className={`px-2 py-1 rounded text-xs ${
                                                    doc.extractionStatus === "complete"
                                                        ? "bg-green-100 text-green-700"
                                                        : doc.extractionStatus === "error"
                                                        ? "bg-red-100 text-red-700"
                                                        : "bg-yellow-100 text-yellow-700"
                                                }`}
                                            >
                                                {doc.extractionStatus}
                                            </span>
                                        </td>
                                        <td className="p-3 text-gray-500 text-xs">
                                            {formatDate(doc.createdAt)}
                                        </td>
                                        <td className="p-3 text-right">
                                            <button
                                                onClick={() => setDeleteSourceDocId(doc.id)}
                                                className="p-1 text-red-500 hover:bg-red-50 rounded"
                                            >
                                                <Trash2 className="h-4 w-4" />
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

            {/* Confirm Dialogs */}
            <ConfirmDialog
                isOpen={!!deleteProjectId}
                onClose={() => setDeleteProjectId(null)}
                onConfirm={handleDeleteProject}
                title="Delete Project?"
                description="This will permanently delete the project and all its features, specifications, and documents. This cannot be undone."
                confirmLabel="Delete"
                variant="danger"
                isLoading={isDeleting}
            />

            <ConfirmDialog
                isOpen={!!deleteSourceDocId}
                onClose={() => setDeleteSourceDocId(null)}
                onConfirm={handleDeleteSourceDoc}
                title="Delete Source Document?"
                description="This will permanently delete this source document. The features and specifications created from it will remain."
                confirmLabel="Delete"
                variant="danger"
                isLoading={isDeleting}
            />

            <ConfirmDialog
                isOpen={showDeleteAutoGenerated}
                onClose={() => setShowDeleteAutoGenerated(false)}
                onConfirm={handleDeleteAutoGenerated}
                title="Delete All Auto-Generated Content?"
                description="This will delete all features and specifications that were created from document extraction across ALL projects. This cannot be undone."
                confirmLabel="Delete All"
                variant="danger"
                isLoading={isDeleting}
            />

            <ConfirmDialog
                isOpen={showCleanupOrphaned}
                onClose={() => setShowCleanupOrphaned(false)}
                onConfirm={handleCleanupOrphaned}
                title="Cleanup Orphaned Data?"
                description="This will find and delete any orphaned features, specifications, messages, and artifacts that no longer have a parent record."
                confirmLabel="Cleanup"
                variant="warning"
                isLoading={isDeleting}
            />

            <ConfirmDialog
                isOpen={showDeleteAll}
                onClose={() => setShowDeleteAll(false)}
                onConfirm={handleDeleteAll}
                title="DELETE ALL DATA?"
                description="This will PERMANENTLY DELETE all projects, features, specifications, messages, artifacts, and documents from the entire database. This action CANNOT be undone. Are you absolutely sure?"
                confirmLabel="DELETE EVERYTHING"
                variant="danger"
                isLoading={isDeleting}
            />
        </div>
    );
}

function StatCard({
    icon: Icon,
    label,
    value,
    highlight,
}: {
    icon: typeof Database;
    label: string;
    value: number | string;
    highlight?: boolean;
}) {
    return (
        <div
            className={`p-4 rounded-lg border ${
                highlight
                    ? "bg-purple-50 border-purple-200"
                    : "bg-white border-gray-200"
            }`}
        >
            <div className="flex items-center gap-2 mb-1">
                <Icon
                    className={`h-4 w-4 ${
                        highlight ? "text-purple-600" : "text-gray-400"
                    }`}
                />
                <span className="text-sm text-gray-600">{label}</span>
            </div>
            <div
                className={`text-2xl font-semibold ${
                    highlight ? "text-purple-700" : "text-gray-900"
                }`}
            >
                {value}
            </div>
        </div>
    );
}
